### ISSUE TITLE
www.dmetar.protectlab.org does not work

### ISSUE THREAD

**Issue by LukasWallrich** [MathiasHarrer/dmetar#14]
Thanks for this package! Just a heads up that the link to [www.dmetar.protectlab.org](http://www.dmetar.protectlab.org/) as shown in the repo details does not work - it shows page not found. Without the www, it works [https://dmetar.protectlab.org/](https://dmetar.protectlab.org/)

**Comment by MathiasHarrer** [comment]
Thanks @LukasWallrich! Should be fixed now. 
Thanks heaps, M
