### ISSUE TITLE
Print method for GOSH diagnostics incorrectly reporting outlier studies for GMM

### ISSUE THREAD

**Issue by dchiu911** [MathiasHarrer/dmetar#16]
Replace `x$outlier.studies.db` with `x$outlier.studies.gmm` [here](https://github.com/MathiasHarrer/dmetar/blob/master/R/print.gosh.diagnostics.R#L56)

**Comment by MathiasHarrer** [comment]
Thanks for the heads up @dchiu911 ! Should be fixed now
