### ISSUE TITLE
find.outliers(m.gen) command not working

### ISSUE THREAD

**Issue by Scoota1997** [MathiasHarrer/dmetar#18]
Hello

When following the tutorial on the ThirdWave dataset. I look for outliers using find.outliers(m.gen)
I keep getting the error: Error in if (x$comb.fixed == TRUE & x$comb.random == FALSE) { : argument is of length zero
I have also tried using the Chernobyl dataset and have the same issue. 

Please help work out what I am doing wrong here?

**Comment by MathiasHarrer** [comment]
Hi there! 

Is it possible that you use an older installation of dmetar? This problem should be fixed in newer versions. Does the problem persist after you have installed the latest version? See https://dmetar.protectlab.org/#installation

Best, M

**Comment by Scoota1997** [comment]
Hello

Yes, that was the issue! Thanks for taking the time to help me solve this. 
And thank you for all your work on this. Your book is great!
