### ISSUE TITLE
Wrongly presented I2 in Influence Analysis

### ISSUE THREAD

**Issue by Chemicalius** [MathiasHarrer/dmetar#9]
In influence analysis plots, I2 is presented as 0.85%, instead of either 0.85 or 85%.
The problem is identified in influence.analysis.R, lines 831 and 835.

Thanks in advance for fixing it.

**Comment by MathiasHarrer** [comment]
Hey Chemicalius,
thanks for mentioning this. This should now be fixed with the latest commit 3ac1f38.
